"""
Local orchestrator: run one TernaVLM stage on a private Kaggle GPU kernel and bring the checkpoint home.

    python kaggle/push.py smoke                  # ~20 min, proves the pipeline
    python kaggle/push.py stage1                 # rerun each session until it prints "finished"
    python kaggle/push.py stage2
    python kaggle/push.py stage1 --no-wait       # just push, poll later with --status
    python kaggle/push.py --status               # print kernel status
    python kaggle/push.py --fetch <run_dir>      # download outputs for a pushed run and version the ckpt dataset

Design (mirrors Boulder_Vision_Platform's runner):
  * the whole repo (ternavlm/, train.py, configs/) is embedded into a single runner_script.py,
    so the kernel needs no GitHub access and stays private;
  * checkpoints persist in a private Kaggle dataset <user>/ternavlm-ckpt as <stage>/latest.pt,
    mounted read-only in the next kernel for --resume / --init;
  * every run gets runs/<UTC>_<stage>/{kernel,output,summary.json}.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
USER = "shivpratap0007"
KERNEL_SLUG = "ternavlm-runner"
KERNEL_TITLE = "TernaVLM Runner"
CKPT_SLUG = "ternavlm-ckpt"
CKPT_TITLE = "TernaVLM Checkpoints"
KERNEL_REF = f"{USER}/{KERNEL_SLUG}"
CKPT_REF = f"{USER}/{CKPT_SLUG}"
RUNS = ROOT / "runs"
EMBED = ["ternavlm/__init__.py", "ternavlm/ops.py", "ternavlm/ternary.py", "ternavlm/vlm.py", "ternavlm/data.py",
         "train.py", "requirements.txt", "configs/smoke.yaml", "configs/stage1.yaml", "configs/stage2.yaml"]
INIT_FROM = {"stage2": "stage1"}
TIMEOUT_S = {"smoke": 3600, "stage1": 43000, "stage2": 43000}
BUDGET_MIN = {"smoke": 40, "stage1": 680, "stage2": 680}


def kaggle(*args, timeout=3600) -> str:
    p = subprocess.run(["kaggle", *args], capture_output=True, text=True, encoding="utf-8", errors="replace",
                       timeout=timeout, env={**os.environ, "PYTHONUTF8": "1"})
    out = (p.stdout or "") + (p.stderr or "")
    if p.returncode != 0:
        raise RuntimeError(f"kaggle {' '.join(args)} failed:\n{out.strip()}")
    return out


def dataset_exists() -> bool:
    try:
        kaggle("datasets", "status", CKPT_REF, timeout=120)
        return True
    except RuntimeError:
        return False


BOOTSTRAP = r'''
# ---- TernaVLM Kaggle bootstrap (auto-generated by kaggle/push.py) ----
import json, os, subprocess, sys, traceback, glob, shutil, time
FILES = json.loads(FILES_JSON)
META = json.loads(META_JSON)
os.makedirs("/kaggle/working/repo", exist_ok=True)
os.chdir("/kaggle/working/repo")
for path, src in FILES.items():
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(src)
print("meta:", json.dumps(META, indent=2), flush=True)
status = "ok"
try:
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-U", "transformers>=4.52", "datasets>=2.20", "pyyaml", "sentencepiece"], check=True)
    import torch, transformers, datasets
    print("torch", torch.__version__, "transformers", transformers.__version__, "datasets", datasets.__version__, flush=True)
    subprocess.run("nvidia-smi; free -g; nproc; df -h /kaggle/working | tail -1", shell=True)
    n_gpu = torch.cuda.device_count()
    stage = META["stage"]
    # find checkpoints mounted from the ternavlm-ckpt dataset (path differs across Kaggle images)
    def find_ckpt(st):
        hits = glob.glob(f"/kaggle/input/**/{st}/latest.pt", recursive=True)
        return hits[0] if hits else None
    os.makedirs(f"ckpt/{stage}", exist_ok=True)
    resume = find_ckpt(stage)
    if resume:
        shutil.copy(resume, f"ckpt/{stage}/latest.pt")   # copy: input is read-only, trainer overwrites in place
        print("resuming from", resume, flush=True)
    init = None
    if not resume and META.get("init_from"):
        init = find_ckpt(META["init_from"])
        print("init from", init, flush=True)
        if init is None:
            raise RuntimeError(f"stage {stage} needs a {META['init_from']} checkpoint but none is mounted")
    # parquet shards are downloaded one at a time to the 20 GB working disk (see ternavlm/data.py)
    os.environ["TERNAVLM_SHARD_DIR"] = "/kaggle/working/shards"
    launcher = [sys.executable, "-m", "torch.distributed.run", f"--nproc_per_node={n_gpu}"] if n_gpu > 1 else [sys.executable]
    cmd = launcher + ["train.py", "--config", f"configs/{stage}.yaml", "--resume", f"ckpt/{stage}/latest.pt",
                      "--time-budget-min", str(META["budget_min"])]
    if init:
        cmd += ["--init", init]
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)
except Exception:
    traceback.print_exc()
    status = "failed"
finally:
    # export the checkpoint(s) to the kernel output root as <stage>/latest.pt
    for p in glob.glob("ckpt/*/latest.pt") + glob.glob("ckpt/*/diag.jsonl"):
        st = p.split("/")[1]
        os.makedirs(f"/kaggle/working/{st}", exist_ok=True)
        shutil.copy(p, f"/kaggle/working/{st}/{os.path.basename(p)}")
        print("exported", p, os.path.getsize(p) // 2**20, "MB", flush=True)
    with open("/kaggle/working/tv_status.json", "w") as f:
        json.dump({"status": status, "meta": META}, f)
    shutil.rmtree("/kaggle/working/repo", ignore_errors=True)
    shutil.rmtree("/kaggle/working/shards", ignore_errors=True)   # never upload data shards as kernel output
    print("JOB STATUS:", status, flush=True)
'''


def build_kernel_dir(stage: str, run_dir: Path, with_ckpt: bool) -> Path:
    kd = run_dir / "kernel"
    kd.mkdir(parents=True, exist_ok=True)
    files = {p: (ROOT / p).read_text(encoding="utf-8") for p in EMBED}
    meta = {"stage": stage, "init_from": INIT_FROM.get(stage), "budget_min": BUDGET_MIN[stage],
            "pushed_at": run_dir.name}
    script = ("# Auto-generated by kaggle/push.py - do not edit.\n"
              f"FILES_JSON = {json.dumps(json.dumps(files))}\n"
              f"META_JSON = {json.dumps(json.dumps(meta))}\n" + BOOTSTRAP)
    (kd / "runner_script.py").write_text(script, encoding="utf-8")
    km = {"id": KERNEL_REF, "title": KERNEL_TITLE, "code_file": "runner_script.py", "language": "python",
          "kernel_type": "script", "is_private": True, "enable_gpu": True, "enable_internet": True,
          "dataset_sources": [CKPT_REF] if with_ckpt else [], "kernel_sources": [], "competition_sources": []}
    (kd / "kernel-metadata.json").write_text(json.dumps(km, indent=2), encoding="utf-8")
    return kd


def poll(interval=60, timeout=46000) -> str:
    end = time.time() + timeout
    last = None
    while time.time() < end:
        try:
            raw = kaggle("kernels", "status", KERNEL_REF, timeout=120)
        except RuntimeError as e:
            raw = str(e)
        m = re.search(r'"(\w+)"', raw)
        state = (m.group(1) if m else raw).strip().lower()
        if state != last:
            print(f"[{dt.datetime.now():%H:%M:%S}] kernel status: {state}", flush=True)
            last = state
        if "complete" in state:
            return "complete"
        if "error" in state or "cancel" in state:
            return "error"
        time.sleep(interval)
    return "timeout"


def fetch(run_dir: Path) -> dict:
    out = run_dir / "output"
    out.mkdir(parents=True, exist_ok=True)
    for attempt in range(3):
        try:
            kaggle("kernels", "output", KERNEL_REF, "-p", str(out), timeout=3600)
            break
        except RuntimeError as e:
            print(f"output download attempt {attempt+1} failed: {str(e)[:300]}")
            time.sleep(30)
    result = {"output_dir": str(out)}
    log = out / f"{KERNEL_SLUG}.log"
    if log.exists():
        lines = log.read_text(encoding="utf-8", errors="replace").splitlines()
        result["log_tail"] = lines[-80:]
    st = out / "tv_status.json"
    result["job_status"] = json.loads(st.read_text())["status"] if st.exists() else "unknown"
    ckpts = list(out.glob("*/latest.pt"))
    result["checkpoints"] = [str(c) for c in ckpts]
    if ckpts and result["job_status"] == "ok":
        result["dataset"] = version_ckpt_dataset(out)
    return result


def version_ckpt_dataset(out: Path) -> str:
    """Push <stage>/latest.pt files as a new version of the private ckpt dataset (keeps other stages)."""
    stage_dirs = {c.parent.name: c for c in out.glob("*/latest.pt")}
    folder = RUNS / "_ckpt_dataset"
    if folder.exists():
        # keep previously fetched stages that this run didn't touch
        for old in folder.glob("*/latest.pt"):
            if old.parent.name not in stage_dirs:
                stage_dirs[old.parent.name] = old
    staging = RUNS / "_ckpt_staging"
    shutil.rmtree(staging, ignore_errors=True)
    for st, src in stage_dirs.items():
        (staging / st).mkdir(parents=True, exist_ok=True)
        shutil.copy(src, staging / st / "latest.pt")
    (staging / "dataset-metadata.json").write_text(json.dumps(
        {"title": CKPT_TITLE, "id": CKPT_REF, "licenses": [{"name": "CC0-1.0"}]}, indent=2))
    if dataset_exists():
        msg = kaggle("datasets", "version", "-p", str(staging), "-m", f"update {','.join(stage_dirs)}",
                     "--dir-mode", "zip", timeout=7200)
    else:
        msg = kaggle("datasets", "create", "-p", str(staging), "--dir-mode", "zip", timeout=7200)
    shutil.rmtree(folder, ignore_errors=True)
    shutil.move(str(staging), str(folder))
    print("[dataset]", msg.strip().splitlines()[-1])
    return msg.strip().splitlines()[-1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stage", nargs="?", choices=["smoke", "stage1", "stage2"])
    ap.add_argument("--no-wait", action="store_true")
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--fetch", metavar="RUN_DIR")
    a = ap.parse_args()

    if a.status:
        print(kaggle("kernels", "status", KERNEL_REF, timeout=120).strip())
        return
    if a.fetch:
        print(json.dumps(fetch(Path(a.fetch)), indent=2))
        return
    if not a.stage:
        ap.error("stage required")

    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    run_dir = RUNS / f"{stamp}_{a.stage}"
    with_ckpt = dataset_exists()
    kd = build_kernel_dir(a.stage, run_dir, with_ckpt)
    print(f"pushing {a.stage} (ckpt dataset mounted: {with_ckpt}) from {kd}")
    push = kaggle("kernels", "push", "-p", str(kd), "--accelerator", "NvidiaTeslaT4", "-t", str(TIMEOUT_S[a.stage]),
                  timeout=600)
    summary = {"run_dir": str(run_dir), "stage": a.stage, "pushed_at": stamp, "push_output": push.strip(),
               "status": "pushed", "ckpt_mounted": with_ckpt}
    (run_dir / "summary.json").write_text(json.dumps(summary, indent=2))
    print(push.strip())
    if a.no_wait:
        return
    summary["status"] = poll()
    if summary["status"] in ("complete", "error"):
        summary.update(fetch(run_dir))
    (run_dir / "summary.json").write_text(json.dumps(summary, indent=2))
    print(json.dumps({k: v for k, v in summary.items() if k != "log_tail"}, indent=2))
    print("\n".join(summary.get("log_tail", [])[-40:]))


if __name__ == "__main__":
    main()
